CREATE TYPE "tiger_den"."content_type" AS ENUM('youtube_video', 'blog_post', 'case_study', 'website_content', 'third_party', 'other');--> statement-breakpoint
CREATE TYPE "tiger_den"."source" AS ENUM('manual', 'csv_import', 'cms_api', 'asana_webhook');--> statement-breakpoint
CREATE TABLE "tiger_den"."account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tiger_den"."campaigns" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "campaigns_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "tiger_den"."content_campaigns" (
	"content_item_id" uuid NOT NULL,
	"campaign_id" uuid NOT NULL,
	CONSTRAINT "content_campaigns_content_item_id_campaign_id_pk" PRIMARY KEY("content_item_id","campaign_id")
);
--> statement-breakpoint
CREATE TABLE "tiger_den"."content_items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"current_url" text NOT NULL,
	"previous_urls" text[],
	"content_type" "tiger_den"."content_type" NOT NULL,
	"publish_date" date,
	"description" text,
	"author" text,
	"target_audience" text,
	"tags" text[],
	"source" "tiger_den"."source" DEFAULT 'manual' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_user_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tiger_den"."post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tiger_den"."post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"created_by_id" varchar(255) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "tiger_den"."session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "tiger_den"."user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "tiger_den"."verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "tiger_den"."account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "tiger_den"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tiger_den"."content_campaigns" ADD CONSTRAINT "content_campaigns_content_item_id_content_items_id_fk" FOREIGN KEY ("content_item_id") REFERENCES "tiger_den"."content_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tiger_den"."content_campaigns" ADD CONSTRAINT "content_campaigns_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "tiger_den"."campaigns"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tiger_den"."post" ADD CONSTRAINT "post_created_by_id_user_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "tiger_den"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tiger_den"."session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "tiger_den"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "content_items_current_url_idx" ON "tiger_den"."content_items" USING btree ("current_url");--> statement-breakpoint
CREATE INDEX "content_items_content_type_idx" ON "tiger_den"."content_items" USING btree ("content_type");--> statement-breakpoint
CREATE INDEX "content_items_publish_date_idx" ON "tiger_den"."content_items" USING btree ("publish_date");--> statement-breakpoint
CREATE INDEX "content_items_created_at_idx" ON "tiger_den"."content_items" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "tiger_den"."post" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX "name_idx" ON "tiger_den"."post" USING btree ("name");